### ISSUE TITLE
Proceed to Cart overlapping with the last item

### ISSUE THREAD

**Issue by KartikeySharma** [AlbinoB/RestaurantApp#10]
When the recycler view has items which exceed the page size, the Proceed to Cart button overlaps and comes in front of the last item in the list.

![BeforeAddingItems](https://user-images.githubusercontent.com/36632816/87695912-be0cc900-c7ad-11ea-93ad-f6ed8c4369d1.jpeg)

![AfterAddingItems](https://user-images.githubusercontent.com/36632816/87695909-bcdb9c00-c7ad-11ea-8793-c5611482b2f2.jpeg)

**Comment by AlbinoB** [comment]
I've merged your code
