### ISSUE TITLE
Some error occured

### ISSUE THREAD

**Issue by abhilashkaranthm** [AlbinoB/RestaurantApp#13]
Hi Sir,

I am getting "Some error occured" during registration. Can you please share all .sql files, it will be more helpful.

**Comment by AlbinoB** [comment]
Hi there, all the files are present. Do you want the database scripts?

**Comment by tony-stark-85** [comment]
Yes, please share 5he the database file

**Comment by AlbinoB** [comment]
I have added the sql file in the master branch.
