### ISSUE TITLE
IPs " 404 not found" response

### ISSUE THREAD

**Issue by acciobugs** [AlbinoB/RestaurantApp#16]
Hi!
Is the IP specified in the network_config file working?
I want to register a user but the response error is a 404 not found.

**Comment by AlbinoB** [comment]
Hi ibarrionuevo, I have shutdown my EC2 AWS instance, please spin up the server locally using XAMM and use https://ngrok.com
 to get a secure tunnel to access your api's from outside your local network.

Second option is you host your own EC2 server on AWS and do the Mapping of the IP.

 Mapping of IP must be done in in two files
1. RestaurantApp/app/src/main/res/xml/network_security_config.xml
2. RestaurantApp/app/src/main/res/values/strings.xml (commented code is used for local testing as per your local IP  -master branch) 

If you want to see the fully functioning App switch the InternshalTraining branch. -> API server is hosted by Internshala and is active.
