### ISSUE TITLE
How to fix this!!

### ISSUE THREAD

**Issue by adityaHedaoo** [AlbinoB/RestaurantApp#8]
On clicking "proceed to cart" button app crashes and shows this error

Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.aditya1.myfoodapplication.Fragments.HomeFragment: could not find Fragment constructor

![image](https://user-images.githubusercontent.com/67869137/86536267-cdfdf080-bf03-11ea-88af-253fa239525c.png)

HomeFragment ->
![image](https://user-images.githubusercontent.com/67869137/86536272-e110c080-bf03-11ea-9433-674a17402a58.png)

**Comment by AlbinoB** [comment]
Which branch are you working on?

**Comment by AlbinoB** [comment]
Send me the code of mainactivity line 37.

**Comment by adityaHedaoo** [comment]
Thnks but the error is gone and now I am facing  different error. xD

**Comment by adityaHedaoo** [comment]
Success in cart activity is getting false and errorMessage is  toasted
![image](https://user-images.githubusercontent.com/67869137/86724657-99468200-c046-11ea-8397-37874ba637cb.png)
![image](https://user-images.githubusercontent.com/67869137/86724844-c6933000-c046-11ea-86a4-071a372c9cca.png)

**Comment by AlbinoB** [comment]
No Follow up, hence closing this issue.
